### ISSUE TITLE
Hard-coded Config location

### ISSUE THREAD

**Issue by d3dc** [harrysolovay/rescripts#15]
In my use-case, I want to re-package CRA with some different configuration and have the end-user use it in exactly the same way.

[Currently the CLI looks for the config in two hardcoded places](https://github.com/rescripts/rescripts/blob/master/packages/cli/loader.js#L19) both of which I can't think of a way to monkey-patch without a visible config file or package field.

This partially leads to #14 - If I do have to expose the rescripts configuration, I'd like for it to be clean and easy to override.

[My initial work has been to completely abstract configuration ala CRA, but have dotfile support.](https://github.com/d3dc/react-flying-saucer/blob/master/packages/react-flying-saucer/bin/scripts.js)

After looking at this project, I like the rescripts api and having a package field with a pre-configured preset might be a good way to leave breadcrumbs to a potential best practice. But I worry about caveats such as the one I bring up in #14.

**Comment by harrysolovay** [comment]
By caveat in #14 , do you mean the inability to have multiple rescripts adding onto a single Babel config without overriding one another's edits?... I'm not sure I fully-understand.

And in terms of footprint, there's no way to monkeypatch `react-scripts` without some intermediary execution step. Maybe a CLI would be cleaner for your project? I know exactly what you're talking about by the way: it'd be so nice to be able to patch `react-scripts` without having to replace `react-scripts` calls in the `package.json` with `rescripts` calls. Unfortunately, the current implementation is the most DX-friendly.

And in terms of specifying the Rescripts configuration root... the current implementation is also the most DX-friendly (to my knowledge). If you can think of a better DX, please let me know so that I can investigate and potentially bring it to life. Although, I really don't think the package field is too intrusive... but I understand that you'd prefer a truly zero-config way. I guess the only other way would be to traverse the project and node_modules for packages with the keyword `rescript`... but then there's the issue of deciding between multiple rescripts. It's a tricky beast. What're your thoughts?

**Comment by harrysolovay** [comment]
I'm not following. Please re-explain the problem you're having and what you're trying to achieve.

**Comment by d3dc** [comment]
I am considering switching from [@craco/craco](https://github.com/sharegate/craco) another alternative to `react-app-rewired` because it's not being maintained and I like the `rescripts` api a lot.

If I were to switch, I do not see a way to be "zero-config". **This is what I would want to achieve to simply migrate.**

I am currently able to be "zero-config" because I pass my config file location as a command line argument to `craco`.

---

I like the api of `rescripts` and one "nice to have" would be adding the "rescripts" field in `package.json` so it can be amended _after my `create-react-flying-saucer` script is ran_.

From your suggestions, the end-user would see one of the two options from my previous post.

**Comment by d3dc** [comment]
I could definitely monkey-patch `require.resolve` to modify the `rescripts` field before `@rescripts/cli` is run - but that's really dirty...

**Comment by harrysolovay** [comment]
@d3dc I don't think monkey-patching `require.resolve` is a great solution. And I don't think you'll want to add onto the `package.json` after project initialization, rather than editing the `create-react-flying-saucer` template... tbh I'm still unsure of how to help you. If you could please lay out the problem again, I'll try to be of some help :) also, thanks for the kind words about liking the Rescripts API!

**Comment by d3dc** [comment]
My dumb monkey brain wants a command-line flag to change where `rescripts` looks for `.rescriptssrc.js`.

My other brain thinks there's a more elegant solution.

**Comment by harrysolovay** [comment]
Ahh I see what you're saying. That wouldn't be a bad feature, but it would mean a difference between executing `rescripts` and `react-scripts`, which idk how I feel about. What're your thoughts? Also, what problem does that solve for your use case (you mentioned something having to do with deeply-nested rescripts)?

**Comment by d3dc** [comment]
[Here's an example project's package.json](https://github.com/d3dc/react-flying-saucer/blob/master/examples/todos/package.json)

As mentioned, `react-flying-saucer` just changes `process.args` and calls `craco` (or `@rescripts/cli`)

I think your "deeply-nested" thought comes from me talking about _merging_ babel configs.

Currently, I set `babelConfig.options.babelrc` and `babel` will merge `.babelrc` with my hidden "rescript" babel config.

The person writing the `.babelrc` file might not be me. They might not know what presets I add. Thats ok, because its merged.

If I wanted to expose the rescript api to that person who might not be me, they can shoot themselves in the foot and remove my added presets.

**Comment by harrysolovay** [comment]
Ah I see. It's hard to predict how users will "rescript" the config. They might use a `.babelrc`, they might use a `babel.config.js`, they might opt for their own parser, transformer and generator even. It's impossible to account for the virtually infinite use cases and their potential conflicts with one another.

My advice is to make a new rescript (and PR the rescripts documentation with a link to it :) –– the new rescript could be called `rescript-use-additional-babel-config`, and can add to the babel config without overriding it. Could be used like so:

`.rescriptsrc.js`

```js
module.exports = [
  ['use-babel-config', '.babelrc.js'], // or whatever other config source
  ['use-additional-babel-config', {
    presets: ['babel-preset-react-flying-saucer'],
  }]
]
```

Let me know what you think or if you need more help 👍
