### ISSUE TITLE
Incompatible with CRA default test command

### ISSUE THREAD

**Issue by bfeister** [harrysolovay/rescripts#28]
I noticed a similar issue [over here](https://github.com/harrysolovay/rescripts/issues/17), and despite perhaps being repeat, I wanted to point out that if we're running a fullstack productionized app, it's likely that the default `react-scripts test` command is in use. With regard to extending webpack config to use plugins like [directory-named-webpack-plugin](https://github.com/shaketbaby/directory-named-webpack-plugin), it's problematic that there's no way to mirror the overridden webpack config between the webpack vs. jest runtime environments we get from this module. Any thoughts on this? I just implemented `rescripts` in a large app and then had to pull it out when I found jest tests were failing due to pathing issues which are fine via `directory-named-webpack-plugin` but of course fail to run in jest.

**Comment by harrysolovay** [comment]
@bfeister sorry to hear you had this bad experience. Unfortunately it's tough to mirror that configuration in Jest (given that you're overriding the entry-file conventions via a Webpack plugin, which doesn't get applied during the jest stage). You might benefit from looking into "require highjacking"; edit the default node resolution so that it checks for the directory name and searches for a file by that name instead of 'index.js'.

**Comment by bfeister** [comment]
Nice. Great suggestion, thank you!
